name: dbt-create

#trigger:
#- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: dbtDeploy
  displayName: dbt Deploy
  jobs:
  - job: dbtRun
    displayName: dbt Run
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          addToPath: true
          architecture: 'x64'
      - script: |
          pip install -q --upgrade pip setuptools wheel
          pip install -q --no-cache-dir dbt-core
          pip install -q --no-cache-dir dbt-snowflake --no-use-pep517
          pip install -q --no-cache-dir dbt-synapse
        displayName: Installing pip and dbt
      - script: |
          cp dbtcore_image/profiles.yml dbtproject
        displayName: Setting up dbt profiles.yml
      - script: |
          cd dbtproject/
          ls -l
          dbt debug
          dbt deps
          dbt run
        displayName: Running dbt

