name: dbt-schedule

schedules:
- cron: "0 6 * * *"
  displayName: Every day at 6:00AM (WST)
  always: true

pool:
  vmImage: ubuntu-latest

stages:
- stage: dbtDeploy
  displayName: dbt Deploy
  jobs:
  - job: dbtRun
    displayName: dbt Run
    steps:
      - task: UserPythonVersion@0
        inputs:
          versionSpec: '3.7'
      - script: |
          pip install -q --upgrade pip setuptools wheel
          pip install -q --no-cache-dir dbt-core
          pip install -q --no-cache-dir dbt-snowflake --no-use-pep517
          pip install -q --no-cache-dir dbt-synapse
      - script: dbt deps
      - script: dbt run
