name: dbtcore-azure

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Run a one-line script'
  jobs:  
    - job: DeployInfra
      displayName: Deploy Infra via Terraform
      steps:      
        - script: echo Hello, world!
        - task: TerraformInstaller@0
          inputs:
            terraformVersion: 'latest'