name: dbtcore-azure

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Run a one-line script'
  jobs:  
    - job: DeployInfra
      displayName: Deploy Infra via Terraform
      steps:      
        - task: TerraformInstaller@0
          inputs:
            terraformVersion: 'latest'
        - task: TerraformCLI@0
          inputs:
            command: 'init'
            workingDirectory: 'infra/'
            allowTelemetryCollection: false
        - task: TerraformCLI@0
          inputs:
            command: 'validate'
            workingDirectory: 'infra/'
            allowTelemetryCollection: false
